version: "3.8"

services:
  ms-race:
    image: mongo:latest
    container_name: ms-race
    environment:
      - MONGO_INITDB_DATABASE=db_ms-race
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017